import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '~/styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Terrazone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <script
      src="https://kit.fontawesome.com/d0e0071c1c.js"
      crossOrigin="anonymous"
    ></script>
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
